In [ ]:
import pandas as pd
import numpy as np
import os
import sys

In [ ]:
df_reader = pd.read_csv('/content/drive/MyDrive/TANOVEN/Exported/Concated_Total_Consumption.csv',
                        header=0, iterator=True
                        )

In [ ]:
for df in df_reader:
  display(df.head())
  break

   Unnamed: 0         msisdn             imsi  ...   tc_day29    tc_day30   tc_day31
0           0  6281318059XXX  510101832059XXX  ...  2162111.0   4558875.0  1075032.0
1           1  X2812X10X80XX  51010X1250X80XX  ...   129305.0     33728.0  3906377.0
2           2    628119229XX  X1010921321X0XX  ...     3177.0   5399892.0        0.0
3           3  628XX8XX678XX  5X0X08XX2X678XX  ...     4725.0  92442672.0    31973.0
4           4  6XXX1X35737XX  51010X36X5737XX  ...        0.0    620128.0  2836020.0

[5 rows x 34 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 963688 entries, 0 to 963687
Data columns (total 34 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  963688 non-null  int64
 1   msisdn      963688 non-null  object
 2   imsi        963688 non-null  object
 3   tc_day1     963688 non-null  float64
 4   tc_day2     963688 non-null  float64
 5   tc_day3     963688 non-null  float64
 6   tc_day4     963688 non-null  float64
 7   tc_day5     963688 non-null  float64
 8   tc_day6     963688 non-null  float64
 9   tc_day7     963688 non-null  float64
 10  tc_day8     963688 non-null  float64
 11  tc_day9     963688 non-null  float64
 12  tc_day10    963688 non-null  float64
 13  tc_day11    963688 non-null  float64
 14  tc_day12    963688 non-null  float64
 15  tc_day13    963688 non-null  float64
 16  tc_day14    963688 non-null  float64
 17  tc_day15    963688 non-null  float64
 18  tc_day16    963688 non-null  float64
 19  tc_day17    963688 non-null  float64
 20  tc_day18    963688 non-null  float64
 21  tc_day19    963688 non-null  float64
 22  tc_day20    963688 non-null  float64
 23  tc_day21    963688 non-null  float64
 24  tc_day22    963688 non-null  float64
 25  tc_day23    963688 non-null  float64
 26  tc_day24    963688 non-null  float64
 27  tc_day25    963688 non-null  float64
 28  tc_day26    963688 non-null  float64
 29  tc_day27    963688 non-null  float64
 30  tc_day28    963688 non-null  float64
 31  tc_day29    963688 non-null  float64
 32  tc_day30    963688 non-null  float64
 33  tc_day31    963688 non-null  float64
dtypes: float64(31), int64(1), object(2)
memory usage: 250.0+ MB

In [ ]:
# df.duplicated().sum()

In [ ]:
# df[['msisdn','imsi']].duplicated().sum()

In [ ]:
df.columns

Index(['Unnamed: 0', 'msisdn', 'imsi', 'tc_day1', 'tc_day2', 'tc_day3',
       'tc_day4', 'tc_day5', 'tc_day6', 'tc_day7', 'tc_day8', 'tc_day9',
       'tc_day10', 'tc_day11', 'tc_day12', 'tc_day13', 'tc_day14', 'tc_day15',
       'tc_day16', 'tc_day17', 'tc_day18', 'tc_day19', 'tc_day20', 'tc_day21',
       'tc_day22', 'tc_day23', 'tc_day24', 'tc_day25', 'tc_day26', 'tc_day27',
       'tc_day28', 'tc_day29', 'tc_day30', 'tc_day31'],
      dtype='object')

In [ ]:
ren = df.rename(columns={
    'tc_day1': 1,
    'tc_day2': 2,
    'tc_day3': 3,
    'tc_day4': 4,
    'tc_day5': 5,
    'tc_day6': 6,
    'tc_day7': 7,
    'tc_day8': 8,
    'tc_day9': 9,
    'tc_day10': 10,
    'tc_day11': 11,
    'tc_day12': 12,
    'tc_day13': 13,
    'tc_day14': 14,
    'tc_day15': 15,
    'tc_day16': 16,
    'tc_day17': 17,
    'tc_day18': 18,
    'tc_day19': 19,
    'tc_day20': 20,
    'tc_day21': 21,
    'tc_day22': 22,
    'tc_day23': 23,
    'tc_day24': 24,
    'tc_day25': 25,
    'tc_day26': 26,
    'tc_day27': 27,
    'tc_day28': 28,
    'tc_day29': 29,
    'tc_day30': 30,
    'tc_day31': 31
    })

In [ ]:
col = df.columns[33]

In [ ]:
df.head(50)

    Unnamed: 0         msisdn  ...     tc_day30    tc_day31
0            0  6281318059XXX  ...    4558875.0   1075032.0
1            1  X2812X10X80XX  ...      33728.0   3906377.0
2            2    628119229XX  ...    5399892.0         0.0
3            3  628XX8XX678XX  ...   92442672.0     31973.0
4            4  6XXX1X35737XX  ...     620128.0   2836020.0
5            5  X28X38XX3X4XX  ...     205566.0   9687338.0
6            6  X2852184547XX  ...  249770060.0    640940.0
7            7  628524X208XXX  ...   10871327.0    745172.0
8            8  X28521X4084XX  ...          0.0   2002656.0
9            9  62X12X6X50XXX  ...    5689111.0     15054.0
10          10  6X81XX5X1X1XX  ...          0.0    146619.0
11          11  6X85X1X989XXX  ...      11813.0         0.0
12          12  628125X2541XX  ...     966476.0         0.0
13          13  628X3X53347XX  ...       6093.0   4535877.0
14          14  X2822XX1111XX  ...       1270.0  69978788.0
15          15  62X22607066XX  ...          0.0   6128488.0
16          16  62X229X1303XX  ...   16937936.0     17126.0
17          17  62812415992XX  ...     111067.0   2892477.0
18          18  628X21732XXXX  ...      15510.0         0.0
19          19  6281389X4X1XX  ...     892818.0     24652.0
20          20  62X5213X5X2XX  ...  472489423.0   3503913.0
21          21  62XX2X4X637XX  ...     153750.0   2289415.0
22          22  X28X298X799XX  ...          0.0         0.0
23          23  X2812990310XX  ...          4.0    707689.0
24          24  6X851564398XX  ...      46402.0    139922.0
25          25  X2821X40900XX  ...          0.0  72997098.0
26          26  62812X58553XX  ...       1281.0    119696.0
27          27  62X212XX005XX  ...       2456.0    581947.0
28          28  62823203466XX  ...  110758914.0         0.0
29          29  62X12X37X77XX  ...      25239.0   1384894.0
30          30  6X81X8X555XXX  ...   30596106.0  37713804.0
31          31  62X216X5X0XXX  ...          0.0  17290104.0
32          32  62812884284XX  ...     530194.0         0.0
33          33  628138X455XXX  ...     397653.0  22680281.0
34          34  6X8X11X5153XX  ...     442737.0         0.0
35          35  6281X8X5526XX  ...   12341476.0  87970901.0
36          36  62821118799XX  ...    2168812.0    273051.0
37          37  62822996060XX  ...    9919360.0    370408.0
38          38  628138X782XXX  ...          0.0      8306.0
39          39  6X813100150XX  ...     227407.0        40.0
40          40  62851551771XX  ...   28053721.0         0.0
41          41  6X8X3X63X46XX  ...     319017.0    118855.0
42          42  62822XXX0X5XX  ...      28913.0    897325.0
43          43  628X2987233XX  ...    1558406.0  17415235.0
44          44  6281297X846XX  ...     443134.0         0.0
45          45    628XX9929XX  ...    2970442.0   2312157.0
46          46  62X13XX2103XX  ...   31929147.0    738107.0
47          47  6XX5X107XX7XX  ...     146240.0     70423.0
48          48  62823108616XX  ...          0.0    210654.0
49          49  62822980002XX  ...     207558.0    140478.0

[50 rows x 34 columns]

In [ ]:
print(df.iloc[:, 3:34])

           tc_day1     tc_day2  ...    tc_day30     tc_day31
0            202.0   2164303.0  ...   4558875.0    1075032.0
1         137416.0  22077904.0  ...     33728.0    3906377.0
2        2940787.0   3890527.0  ...   5399892.0          0.0
3         388641.0     51652.0  ...  92442672.0      31973.0
4       18034090.0   2024309.0  ...    620128.0    2836020.0
...            ...         ...  ...         ...          ...
963683     46246.0    464988.0  ...         0.0      74945.0
963684   3666382.0      7585.0  ...  13531106.0     221670.0
963685  32683054.0   7398718.0  ...     11254.0  235106356.0
963686         0.0   4042264.0  ...         0.0    6021441.0
963687    850497.0   6276931.0  ...         0.0     498743.0

[963688 rows x 31 columns]

In [ ]:
#Get Total Consumption Per Day
Day = pd.get_dummies(ren.iloc[:, 3:34])

In [ ]:
Day

                1           2   ...          30           31
0            202.0   2164303.0  ...   4558875.0    1075032.0
1         137416.0  22077904.0  ...     33728.0    3906377.0
2        2940787.0   3890527.0  ...   5399892.0          0.0
3         388641.0     51652.0  ...  92442672.0      31973.0
4       18034090.0   2024309.0  ...    620128.0    2836020.0
...            ...         ...  ...         ...          ...
963683     46246.0    464988.0  ...         0.0      74945.0
963684   3666382.0      7585.0  ...  13531106.0     221670.0
963685  32683054.0   7398718.0  ...     11254.0  235106356.0
963686         0.0   4042264.0  ...         0.0    6021441.0
963687    850497.0   6276931.0  ...         0.0     498743.0

[963688 rows x 31 columns]

In [ ]:
#Check Active Customer Per Day
Day = (Day > 80000).astype(int)

In [ ]:
Day

        1   2   3   4   5   6   7   8   9   ...  23  24  25  26  27  28  29  30  31
0        0   1   1   1   1   1   1   0   1  ...   1   0   1   1   0   1   1   1   1
1        1   1   1   1   1   0   1   1   1  ...   1   1   1   1   0   1   1   0   1
2        1   1   1   1   1   1   1   0   1  ...   0   0   1   1   1   1   0   1   0
3        1   0   1   1   0   0   0   1   1  ...   0   1   0   0   1   0   0   1   0
4        1   1   1   0   1   0   1   1   1  ...   0   0   1   1   0   1   0   1   1
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
963683   0   1   0   1   0   0   1   1   1  ...   0   1   1   0   1   0   1   0   0
963684   1   0   1   1   1   0   1   0   1  ...   1   1   0   1   1   1   0   1   1
963685   1   1   1   1   1   1   0   1   0  ...   1   0   1   1   1   1   0   0   1
963686   0   1   1   1   0   0   0   1   1  ...   1   1   0   1   0   0   1   0   1
963687   1   1   0   1   1   1   0   1   1  ...   0   1   0   1   0   1   1   0   1

[963688 rows x 31 columns]

RFM Calculation

In [ ]:
#Func to get Recencies
def getR(df) :
  Recencies=[]
  for idx, row in df.iterrows() :
    list_col = df.columns
    for col in reversed(list_col):
      if row[col]==1:
        Recencies.append(col)
        break
  return Recencies

In [ ]:
R = getR(Day) #Get R Value

In [ ]:
F = Day.sum(axis=1) #Get Frequent Value

In [ ]:
Day['R'] = R
Day['F'] = F

In [ ]:
Day

        1  2  3  4  5  6  7  8  9  10  ...  24  25  26  27  28  29  30  31   R   F
0       0  1  1  1  1  1  1  0  1   1  ...   0   1   1   0   1   1   1   1  31  21
1       1  1  1  1  1  0  1  1  1   1  ...   1   1   1   0   1   1   0   1  31  22
2       1  1  1  1  1  1  1  0  1   1  ...   0   1   1   1   1   0   1   0  30  20
3       1  0  1  1  0  0  0  1  1   1  ...   1   0   0   1   0   0   1   0  30  16
4       1  1  1  0  1  0  1  1  1   0  ...   0   1   1   0   1   0   1   1  31  19
...    .. .. .. .. .. .. .. .. ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
963683  0  1  0  1  0  0  1  1  1   0  ...   1   1   0   1   0   1   0   0  29  13
963684  1  0  1  1  1  0  1  0  1   0  ...   1   0   1   1   1   0   1   1  31  18
963685  1  1  1  1  1  1  0  1  0   1  ...   0   1   1   1   1   0   0   1  31  24
963686  0  1  1  1  0  0  0  1  1   0  ...   1   0   1   0   0   1   0   1  31  19
963687  1  1  0  1  1  1  0  1  1   0  ...   1   0   1   0   1   1   0   1  31  20

[963688 rows x 33 columns]

In [ ]:
RF = Day.iloc[:, 31:33] #Get R and F

In [ ]:
RF

         R   F
0       31  21
1       31  22
2       30  20
3       30  16
4       31  19
...     ..  ..
963683  29  13
963684  31  18
963685  31  24
963686  31  19
963687  31  20

[963688 rows x 2 columns]

In [ ]:
Data = pd.concat([df,RF],axis=1) #Concat with Main Dataframe

In [ ]:
Data

        Unnamed: 0         msisdn             imsi  ...     tc_day31   R   F
0                0  6281318059XXX  510101832059XXX  ...    1075032.0  31  21
1                1  X2812X10X80XX  51010X1250X80XX  ...    3906377.0  31  22
2                2    628119229XX  X1010921321X0XX  ...          0.0  30  20
3                3  628XX8XX678XX  5X0X08XX2X678XX  ...      31973.0  30  16
4                4  6XXX1X35737XX  51010X36X5737XX  ...    2836020.0  31  19
...            ...            ...              ...  ...          ...  ..  ..
963683      999995  6281288X929XX  510108825X929XX  ...      74945.0  29  13
963684      999996  62822992252XX  5101099722252XX  ...     221670.0  31  18
963685      999997  62X131955X2XX  51010193255X2XX  ...  235106356.0  31  24
963686      999998  X281282330XXX  510108225330XXX  ...    6021441.0  31  19
963687      999999  628121XX628XX  51X1X1X25X628XX  ...     498743.0  31  20

[963688 rows x 36 columns]

In [ ]:
Data['M'] = Data.iloc[:, 3:34].sum(axis=1)/8000 #Monetary Calculation

In [ ]:
Data

        Unnamed: 0         msisdn             imsi  ...   R   F              M
0                0  6281318059XXX  510101832059XXX  ...  31  21  402547.509000
1                1  X2812X10X80XX  51010X1250X80XX  ...  31  22  158951.592750
2                2    628119229XX  X1010921321X0XX  ...  30  20  101280.105500
3                3  628XX8XX678XX  5X0X08XX2X678XX  ...  30  16   34911.497375
4                4  6XXX1X35737XX  51010X36X5737XX  ...  31  19   57436.515750
...            ...            ...              ...  ...  ..  ..            ...
963683      999995  6281288X929XX  510108825X929XX  ...  29  13   31695.393500
963684      999996  62822992252XX  5101099722252XX  ...  31  18   97767.122250
963685      999997  62X131955X2XX  51010193255X2XX  ...  31  24  259382.703125
963686      999998  X281282330XXX  510108225330XXX  ...  31  19  320929.063625
963687      999999  628121XX628XX  51X1X1X25X628XX  ...  31  20   90489.682625

[963688 rows x 37 columns]

In [ ]:
# Data['M'].max()

In [ ]:
# print(np.linspace(18, 31, 11))

In [ ]:
# Data['M'].min()

In [ ]:
Labels = [1,2,3,4,5,6,7,8,9,10]

Binning

In [ ]:
Data['r_bin'] = pd.cut(Data['R'], bins=np.linspace(18, 31, 11),labels=Labels)

In [ ]:
Data['f_bin'] = pd.cut(Data['F'], bins=np.linspace(5, 30, 11),labels=Labels)

In [ ]:
Data['m_bin'] = pd.cut(Data['M'], bins=np.linspace(579.6025, 1259654.202, 11),labels=Labels)

In [ ]:
Data['r_bin'].value_counts()

10    808350
9      92575
8      37506
7      21243
6       2384
5        949
4        564
3         64
2         30
1         17
Name: r_bin, dtype: int64

In [ ]:
Data['m_bin'].value_counts()

1     625814
2     249057
3      62619
4      18037
5       6244
6       1494
7        325
8         73
9         19
10         5
Name: m_bin, dtype: int64

In [ ]:
Data['f_bin'].value_counts()

6     397869
5     210048
7     157664
4     118347
8      61730
3      12789
9       3267
2       1800
10       150
1         23
Name: f_bin, dtype: int64

In [ ]:
Data

        Unnamed: 0         msisdn             imsi  ...  r_bin  f_bin  m_bin
0                0  6281318059XXX  510101832059XXX  ...     10      7      4
1                1  X2812X10X80XX  51010X1250X80XX  ...     10      7      2
2                2    628119229XX  X1010921321X0XX  ...     10      6      1
3                3  628XX8XX678XX  5X0X08XX2X678XX  ...     10      5      1
4                4  6XXX1X35737XX  51010X36X5737XX  ...     10      6      1
...            ...            ...              ...  ...    ...    ...    ...
963683      999995  6281288X929XX  510108825X929XX  ...      9      4      1
963684      999996  62822992252XX  5101099722252XX  ...     10      6      1
963685      999997  62X131955X2XX  51010193255X2XX  ...     10      8      3
963686      999998  X281282330XXX  510108225330XXX  ...     10      6      3
963687      999999  628121XX628XX  51X1X1X25X628XX  ...     10      6      1

[963688 rows x 40 columns]

In [ ]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 963688 entries, 0 to 963687
Data columns (total 40 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  963688 non-null  int64
 1   msisdn      963688 non-null  object
 2   imsi        963688 non-null  object
 3   tc_day1     963688 non-null  float64
 4   tc_day2     963688 non-null  float64
 5   tc_day3     963688 non-null  float64
 6   tc_day4     963688 non-null  float64
 7   tc_day5     963688 non-null  float64
 8   tc_day6     963688 non-null  float64
 9   tc_day7     963688 non-null  float64
 10  tc_day8     963688 non-null  float64
 11  tc_day9     963688 non-null  float64
 12  tc_day10    963688 non-null  float64
 13  tc_day11    963688 non-null  float64
 14  tc_day12    963688 non-null  float64
 15  tc_day13    963688 non-null  float64
 16  tc_day14    963688 non-null  float64
 17  tc_day15    963688 non-null  float64
 18  tc_day16    963688 non-null  float64
 19  tc_day17    963688 non-null  float64
 20  tc_day18    963688 non-null  float64
 21  tc_day19    963688 non-null  float64
 22  tc_day20    963688 non-null  float64
 23  tc_day21    963688 non-null  float64
 24  tc_day22    963688 non-null  float64
 25  tc_day23    963688 non-null  float64
 26  tc_day24    963688 non-null  float64
 27  tc_day25    963688 non-null  float64
 28  tc_day26    963688 non-null  float64
 29  tc_day27    963688 non-null  float64
 30  tc_day28    963688 non-null  float64
 31  tc_day29    963688 non-null  float64
 32  tc_day30    963688 non-null  float64
 33  tc_day31    963688 non-null  float64
 34  R           963688 non-null  int64
 35  F           963688 non-null  int64
 36  M           963688 non-null  float64
 37  r_bin       963682 non-null  category
 38  f_bin       963687 non-null  category
 39  m_bin       963687 non-null  category
dtypes: category(3), float64(32), int64(3), object(2)
memory usage: 274.8+ MB

In [ ]:
Data[['r_bin','f_bin','m_bin']] = Data[['r_bin','f_bin','m_bin']].astype(float)

In [ ]:
Data

        Unnamed: 0         msisdn             imsi  ...  r_bin  f_bin  m_bin
0                0  6281318059XXX  510101832059XXX  ...   10.0    7.0    4.0
1                1  X2812X10X80XX  51010X1250X80XX  ...   10.0    7.0    2.0
2                2    628119229XX  X1010921321X0XX  ...   10.0    6.0    1.0
3                3  628XX8XX678XX  5X0X08XX2X678XX  ...   10.0    5.0    1.0
4                4  6XXX1X35737XX  51010X36X5737XX  ...   10.0    6.0    1.0
...            ...            ...              ...  ...    ...    ...    ...
963683      999995  6281288X929XX  510108825X929XX  ...    9.0    4.0    1.0
963684      999996  62822992252XX  5101099722252XX  ...   10.0    6.0    1.0
963685      999997  62X131955X2XX  51010193255X2XX  ...   10.0    8.0    3.0
963686      999998  X281282330XXX  510108225330XXX  ...   10.0    6.0    3.0
963687      999999  628121XX628XX  51X1X1X25X628XX  ...   10.0    6.0    1.0

[963688 rows x 40 columns]

In [ ]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 963688 entries, 0 to 963687
Data columns (total 40 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  963688 non-null  int64
 1   msisdn      963688 non-null  object
 2   imsi        963688 non-null  object
 3   tc_day1     963688 non-null  float64
 4   tc_day2     963688 non-null  float64
 5   tc_day3     963688 non-null  float64
 6   tc_day4     963688 non-null  float64
 7   tc_day5     963688 non-null  float64
 8   tc_day6     963688 non-null  float64
 9   tc_day7     963688 non-null  float64
 10  tc_day8     963688 non-null  float64
 11  tc_day9     963688 non-null  float64
 12  tc_day10    963688 non-null  float64
 13  tc_day11    963688 non-null  float64
 14  tc_day12    963688 non-null  float64
 15  tc_day13    963688 non-null  float64
 16  tc_day14    963688 non-null  float64
 17  tc_day15    963688 non-null  float64
 18  tc_day16    963688 non-null  float64
 19  tc_day17    963688 non-null  float64
 20  tc_day18    963688 non-null  float64
 21  tc_day19    963688 non-null  float64
 22  tc_day20    963688 non-null  float64
 23  tc_day21    963688 non-null  float64
 24  tc_day22    963688 non-null  float64
 25  tc_day23    963688 non-null  float64
 26  tc_day24    963688 non-null  float64
 27  tc_day25    963688 non-null  float64
 28  tc_day26    963688 non-null  float64
 29  tc_day27    963688 non-null  float64
 30  tc_day28    963688 non-null  float64
 31  tc_day29    963688 non-null  float64
 32  tc_day30    963688 non-null  float64
 33  tc_day31    963688 non-null  float64
 34  R           963688 non-null  int64
 35  F           963688 non-null  int64
 36  M           963688 non-null  float64
 37  r_bin       963682 non-null  float64
 38  f_bin       963687 non-null  float64
 39  m_bin       963687 non-null  float64
dtypes: float64(35), int64(3), object(2)
memory usage: 294.1+ MB

In [ ]:
Data['Score'] = Data[['r_bin','f_bin','m_bin']].sum(axis=1) #RFM Score Calculation

In [ ]:
Data

        Unnamed: 0         msisdn             imsi  ...  f_bin  m_bin  Score
0                0  6281318059XXX  510101832059XXX  ...    7.0    4.0   21.0
1                1  X2812X10X80XX  51010X1250X80XX  ...    7.0    2.0   19.0
2                2    628119229XX  X1010921321X0XX  ...    6.0    1.0   17.0
3                3  628XX8XX678XX  5X0X08XX2X678XX  ...    5.0    1.0   16.0
4                4  6XXX1X35737XX  51010X36X5737XX  ...    6.0    1.0   17.0
...            ...            ...              ...  ...    ...    ...    ...
963683      999995  6281288X929XX  510108825X929XX  ...    4.0    1.0   14.0
963684      999996  62822992252XX  5101099722252XX  ...    6.0    1.0   17.0
963685      999997  62X131955X2XX  51010193255X2XX  ...    8.0    3.0   21.0
963686      999998  X281282330XXX  510108225330XXX  ...    6.0    3.0   19.0
963687      999999  628121XX628XX  51X1X1X25X628XX  ...    6.0    1.0   17.0

[963688 rows x 41 columns]

In [ ]:
Data['Score'].describe()

count    963688.000000
mean         17.013201
std           1.720051
min           3.000000
25%          16.000000
50%          17.000000
75%          18.000000
max          29.000000
Name: Score, dtype: float64

In [ ]:
# Data['Label'] = (Data['Score'] >= 17.01).astype(int)

In [ ]:
Labell=['Churn','Loyal']

In [ ]:
# Data['Label'] = Data['Label'].replace([1,0],['Loyal','Churn'])

In [ ]:
Data['Label'] = pd.cut(Data['Score'], bins=np.linspace(1, 30, 3),labels=Labell) #Labeling

In [ ]:
Data

        Unnamed: 0         msisdn             imsi  ...  m_bin  Score  Label
0                0  6281318059XXX  510101832059XXX  ...    4.0   21.0  Loyal
1                1  X2812X10X80XX  51010X1250X80XX  ...    2.0   19.0  Loyal
2                2    628119229XX  X1010921321X0XX  ...    1.0   17.0  Loyal
3                3  628XX8XX678XX  5X0X08XX2X678XX  ...    1.0   16.0  Loyal
4                4  6XXX1X35737XX  51010X36X5737XX  ...    1.0   17.0  Loyal
...            ...            ...              ...  ...    ...    ...    ...
963683      999995  6281288X929XX  510108825X929XX  ...    1.0   14.0  Churn
963684      999996  62822992252XX  5101099722252XX  ...    1.0   17.0  Loyal
963685      999997  62X131955X2XX  51010193255X2XX  ...    3.0   21.0  Loyal
963686      999998  X281282330XXX  510108225330XXX  ...    3.0   19.0  Loyal
963687      999999  628121XX628XX  51X1X1X25X628XX  ...    1.0   17.0  Loyal

[963688 rows x 42 columns]

In [ ]:
Data['Label'].value_counts()

Loyal    802540
Churn    161148
Name: Label, dtype: int64

In [ ]:
Data.to_csv('/content/drive/MyDrive/TANOVEN/Exported/Labeled2_Dataset.csv', header=True, mode='a') #Export to Csv